### Dependencies

In [19]:
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.preprocessing import LabelEncoder

### Load Data

In [20]:
train_df = pd.read_csv('./Resources/2019loans.csv')
test_df = pd.read_csv('./Resources/2020Q1loans.csv')

### Checking the head

In [21]:
train_df.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,pymnt_plan,dti,delinq_2yrs,inq_last_6mths,...,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag,target
0,7000.0,0.1894,256.38,MORTGAGE,75000.0,Not Verified,n,28.62,0.0,2.0,...,87.5,0.0,0.0,352260.0,62666.0,35000.0,10000.0,N,N,low_risk
1,40000.0,0.1614,975.71,MORTGAGE,102000.0,Source Verified,n,11.72,2.0,0.0,...,0.0,0.0,0.0,294664.0,109911.0,9000.0,71044.0,N,N,low_risk
2,11000.0,0.2055,294.81,RENT,45000.0,Verified,n,37.25,1.0,3.0,...,7.7,0.0,0.0,92228.0,36007.0,33000.0,46328.0,N,N,low_risk
3,4000.0,0.1612,140.87,MORTGAGE,38000.0,Not Verified,n,42.89,1.0,0.0,...,100.0,0.0,0.0,284273.0,52236.0,13500.0,52017.0,N,N,low_risk
4,14000.0,0.1797,505.93,MORTGAGE,43000.0,Source Verified,n,22.16,1.0,0.0,...,25.0,0.0,0.0,120280.0,88147.0,33300.0,78680.0,N,N,low_risk

In [22]:
test_df.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,pymnt_plan,dti,delinq_2yrs,inq_last_6mths,...,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag,target
0,40000.0,0.1033,856.40,RENT,128700.0,Source Verified,n,12.47,0.0,1.0,...,57.1,0.0,0.0,63915.0,49510.0,49400.0,14515.0,Y,N,low_risk
1,24450.0,0.1430,572.72,MORTGAGE,44574.0,Not Verified,n,15.05,0.0,1.0,...,0.0,0.0,0.0,136425.0,19439.0,15500.0,18925.0,N,N,low_risk
2,13500.0,0.1430,316.23,OWN,60000.0,Not Verified,n,28.72,0.0,0.0,...,0.0,0.0,0.0,82124.0,65000.0,5400.0,61724.0,Y,N,low_risk
3,10625.0,0.1774,268.31,RENT,60000.0,Verified,n,15.70,0.0,4.0,...,20.0,0.0,0.0,54855.0,50335.0,23200.0,26255.0,N,N,low_risk
4,6375.0,0.1862,232.46,RENT,60000.0,Source Verified,n,35.50,0.0,0.0,...,75.0,0.0,0.0,90445.0,56541.0,15300.0,72345.0,N,N,low_risk

In [23]:
# Viewing Columns - training data
train_df.columns

Index(['loan_amnt', 'int_rate', 'installment', 'home_ownership', 'annual_inc',
       'verification_status', 'pymnt_plan', 'dti', 'delinq_2yrs',
       'inq_last_6mths', 'open_acc', 'pub_rec', 'revol_bal', 'total_acc',
       'initial_list_status', 'out_prncp', 'out_prncp_inv', 'total_pymnt',
       'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int',
       'total_rec_late_fee', 'recoveries', 'collection_recovery_fee',
       'last_pymnt_amnt', 'collections_12_mths_ex_med', 'policy_code',
       'application_type', 'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal',
       'open_acc_6m', 'open_act_il', 'open_il_12m', 'open_il_24m',
       'mths_since_rcnt_il', 'total_bal_il', 'il_util', 'open_rv_12m',
       'open_rv_24m', 'max_bal_bc', 'all_util', 'total_rev_hi_lim', 'inq_fi',
       'total_cu_tl', 'inq_last_12m', 'acc_open_past_24mths', 'avg_cur_bal',
       'bc_open_to_buy', 'bc_util', 'chargeoff_within_12_mths', 'delinq_amnt',
       'mo_sin_old_il_acct', 'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op',
       'mo_sin_rcnt_tl', 'mort_acc', 'mths_since_recent_bc',
       'mths_since_recent_inq', 'num_accts_ever_120_pd', 'num_actv_bc_tl',
       'num_actv_rev_tl', 'num_bc_sats', 'num_bc_tl', 'num_il_tl',
       'num_op_rev_tl', 'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_sats',
       'num_tl_120dpd_2m', 'num_tl_30dpd', 'num_tl_90g_dpd_24m',
       'num_tl_op_past_12m', 'pct_tl_nvr_dlq', 'percent_bc_gt_75',
       'pub_rec_bankruptcies', 'tax_liens', 'tot_hi_cred_lim',
       'total_bal_ex_mort', 'total_bc_limit', 'total_il_high_credit_limit',
       'hardship_flag', 'debt_settlement_flag', 'target'],
      dtype='object')

In [24]:
# Viewing Columns - testing data
test_df.columns

Index(['loan_amnt', 'int_rate', 'installment', 'home_ownership', 'annual_inc',
       'verification_status', 'pymnt_plan', 'dti', 'delinq_2yrs',
       'inq_last_6mths', 'open_acc', 'pub_rec', 'revol_bal', 'total_acc',
       'initial_list_status', 'out_prncp', 'out_prncp_inv', 'total_pymnt',
       'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int',
       'total_rec_late_fee', 'recoveries', 'collection_recovery_fee',
       'last_pymnt_amnt', 'collections_12_mths_ex_med', 'policy_code',
       'application_type', 'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal',
       'open_acc_6m', 'open_act_il', 'open_il_12m', 'open_il_24m',
       'mths_since_rcnt_il', 'total_bal_il', 'il_util', 'open_rv_12m',
       'open_rv_24m', 'max_bal_bc', 'all_util', 'total_rev_hi_lim', 'inq_fi',
       'total_cu_tl', 'inq_last_12m', 'acc_open_past_24mths', 'avg_cur_bal',
       'bc_open_to_buy', 'bc_util', 'chargeoff_within_12_mths', 'delinq_amnt',
       'mo_sin_old_il_acct', 'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op',
       'mo_sin_rcnt_tl', 'mort_acc', 'mths_since_recent_bc',
       'mths_since_recent_inq', 'num_accts_ever_120_pd', 'num_actv_bc_tl',
       'num_actv_rev_tl', 'num_bc_sats', 'num_bc_tl', 'num_il_tl',
       'num_op_rev_tl', 'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_sats',
       'num_tl_120dpd_2m', 'num_tl_30dpd', 'num_tl_90g_dpd_24m',
       'num_tl_op_past_12m', 'pct_tl_nvr_dlq', 'percent_bc_gt_75',
       'pub_rec_bankruptcies', 'tax_liens', 'tot_hi_cred_lim',
       'total_bal_ex_mort', 'total_bc_limit', 'total_il_high_credit_limit',
       'hardship_flag', 'debt_settlement_flag', 'target'],
      dtype='object')

### Preprocessing

##### Training Data Set

In [25]:
# Seperating X training data
X = train_df[['loan_amnt', 'int_rate', 'installment', 'home_ownership', 'annual_inc',
       'verification_status', 'pymnt_plan', 'dti', 'delinq_2yrs',
       'inq_last_6mths', 'open_acc', 'pub_rec', 'revol_bal', 'total_acc',
       'initial_list_status', 'out_prncp', 'out_prncp_inv', 'total_pymnt',
       'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int',
       'total_rec_late_fee', 'recoveries', 'collection_recovery_fee',
       'last_pymnt_amnt', 'collections_12_mths_ex_med', 'policy_code',
       'application_type', 'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal',
       'open_acc_6m', 'open_act_il', 'open_il_12m', 'open_il_24m',
       'mths_since_rcnt_il', 'total_bal_il', 'il_util', 'open_rv_12m',
       'open_rv_24m', 'max_bal_bc', 'all_util', 'total_rev_hi_lim', 'inq_fi',
       'total_cu_tl', 'inq_last_12m', 'acc_open_past_24mths', 'avg_cur_bal',
       'bc_open_to_buy', 'bc_util', 'chargeoff_within_12_mths', 'delinq_amnt',
       'mo_sin_old_il_acct', 'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op',
       'mo_sin_rcnt_tl', 'mort_acc', 'mths_since_recent_bc',
       'mths_since_recent_inq', 'num_accts_ever_120_pd', 'num_actv_bc_tl',
       'num_actv_rev_tl', 'num_bc_sats', 'num_bc_tl', 'num_il_tl',
       'num_op_rev_tl', 'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_sats',
       'num_tl_120dpd_2m', 'num_tl_30dpd', 'num_tl_90g_dpd_24m',
       'num_tl_op_past_12m', 'pct_tl_nvr_dlq', 'percent_bc_gt_75',
       'pub_rec_bankruptcies', 'tax_liens', 'tot_hi_cred_lim',
       'total_bal_ex_mort', 'total_bc_limit', 'total_il_high_credit_limit',
       'hardship_flag', 'debt_settlement_flag']]

In [26]:
# Seperating y training data
y = train_df[['target']]
y

          target
0       low_risk
1       low_risk
2       low_risk
3       low_risk
4       low_risk
5       low_risk
6       low_risk
7       low_risk
8       low_risk
9       low_risk
10      low_risk
11      low_risk
12      low_risk
13      low_risk
14      low_risk
15      low_risk
16      low_risk
17      low_risk
18      low_risk
19      low_risk
20      low_risk
21      low_risk
22      low_risk
23      low_risk
24      low_risk
25      low_risk
26      low_risk
27      low_risk
28      low_risk
29      low_risk
...          ...
12150  high_risk
12151  high_risk
12152  high_risk
12153  high_risk
12154  high_risk
12155  high_risk
12156  high_risk
12157  high_risk
12158  high_risk
12159  high_risk
12160  high_risk
12161  high_risk
12162  high_risk
12163  high_risk
12164  high_risk
12165  high_risk
12166  high_risk
12167  high_risk
12168  high_risk
12169  high_risk
12170  high_risk
12171  high_risk
12172  high_risk
12173  high_risk
12174  high_risk
12175  high_risk
12176  high_risk
12177  high_risk
12178  high_risk
12179  high_risk

[12180 rows x 1 columns]

In [27]:
 # Convert categorical data to numeric and separate target feature for training data
X_dummies = pd.get_dummies(X)

In [28]:
# Converting output labels to 0 and 1
y_label = LabelEncoder().fit_transform(y['target'])
y_label

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

In [29]:
# Checking X_dummies
X_dummies

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,verification_status_Verified,pymnt_plan_n,initial_list_status_f,initial_list_status_w,application_type_Individual,application_type_Joint App,hardship_flag_N,hardship_flag_Y,debt_settlement_flag_N,debt_settlement_flag_Y
0,7000.0,0.1894,256.38,75000.0,28.62,0.0,2.0,20.0,0.0,40414.0,...,0,1,1,0,1,0,1,0,1,0
1,40000.0,0.1614,975.71,102000.0,11.72,2.0,0.0,10.0,0.0,43531.0,...,0,1,0,1,1,0,1,0,1,0
2,11000.0,0.2055,294.81,45000.0,37.25,1.0,3.0,23.0,0.0,8242.0,...,1,1,0,1,1,0,1,0,1,0
3,4000.0,0.1612,140.87,38000.0,42.89,1.0,0.0,7.0,0.0,12767.0,...,0,1,0,1,0,1,1,0,1,0
4,14000.0,0.1797,505.93,43000.0,22.16,1.0,0.0,22.0,0.0,11182.0,...,0,1,0,1,1,0,1,0,1,0
5,6000.0,0.0756,186.81,90500.0,23.48,0.0,0.0,9.0,0.0,7092.0,...,0,1,0,1,1,0,1,0,1,0
6,10500.0,0.2250,293.00,32000.0,16.09,0.0,1.0,10.0,0.0,2269.0,...,1,1,0,1,1,0,1,0,1,0
7,22000.0,0.0819,448.09,92000.0,22.87,0.0,0.0,17.0,0.0,26020.0,...,0,1,0,1,1,0,1,0,1,0
8,10625.0,0.2055,284.76,54100.0,15.53,0.0,2.0,8.0,0.0,9371.0,...,0,1,0,1,0,1,1,0,1,0
9,20000.0,0.2534,591.02,38000.0,19.68,0.0,0.0,4.0,0.0,20770.0,...,0,1,0,1,1,0,1,0,1,0
10,10000.0,0.0881,317.12,192000.0,17.93,0.0,0.0,16.0,0.0,25101.0,...,0,1,0,1,1,0,1,0,1,0
11,5000.0,0.0702,154.44,60000.0,14.56,0.0,0.0,8.0,0.0,478.0,...,0,1,0,1,0,1,1,0,1,0
12,22000.0,0.1180,487.16,120000.0,9.89,0.0,0.0,10.0,0.0,22264.0,...,0,1,0,1,1,0,1,0,1,0
13,8500.0,0.1102,278.36,85000.0,28.02,0.0,0.0,12.0,1.0,13072.0,...,0,1,0,1,1,0,1,0,1,0
14,10625.0,0.1524,369.57,62000.0,11.81,0.0,0.0,8.0,0.0,9415.0,...,0,1,0,1,1,0,1,0,1,0
15,20800.0,0.1308,474.12,65000.0,24.54,0.0,1.0,15.0,1.0,13103.0,...,0,1,0,1,1,0,1,0,1,0
16,28000.0,0.1474,662.31,92000.0,10.14,0.0,0.0,8.0,0.0,13822.0,...,0,1,0,1,1,0,1,0,1,0
17,7500.0,0.2089,282.14,75000.0,25.25,2.0,0.0,18.0,0.0,25506.0,...,0,1,0,1,1,0,1,0,1,0
18,10000.0,0.1894,366.26,150000.0,21.66,2.0,0.0,13.0,0.0,23668.0,...,0,1,0,1,1,0,1,0,1,0
19,20500.0,0.1502,487.91,70000.0,13.32,0.0,0.0,5.0,0.0,7542.0,...,0,1,0,1,0,1,1,0,1,0
20,15000.0,0.2000,397.41,50000.0,25.71,0.0,0.0,7.0,0.0,11006.0,...,1,1,0,1,1,0,1,0,1,0
21,16000.0,0.0646,490.10,50000.0,25.04,0.0,0.0,12.0,0.0,12057.0,...,0,1,0,1,1,0,1,0,1,0
22,6000.0,0.1240,200.44,62000.0,38.50,0.0,1.0,14.0,0.0,38076.0,...,0,1,0,1,1,0,1,0,1,0
23,35000.0,0.1033,1134.79,150000.0,23.48,0.0,0.0,12.0,0.0,31585.0,...,1,1,0,1,1,0,1,0,1,0
24,18000.0,0.1240,404.05,66000.0,35.53,0.0,0.0,10.0,0.0,20318.0,...,0,1,1,0,1,0,1,0,1,0
25,25000.0,0.1180,553.59,87000.0,35.50,0.0,1.0,8.0,0.0,6898.0,...,0,1,0,1,0,1,1,0,1,0
26,12000.0,0.1774,432.27,39836.0,17.35,0.0,0.0,8.0,0.0,11048.0,...,1,1,0,1,1,0,1,0,1,0
27,4400.0,0.0646,134.78,51000.0,9.39,0.0,1.0,8.0,0.0,4173.0,...,0,1,0,1,1,0,1,0,1,0
28,2000.0,0.1430,68.65,49300.0,32.42,0.0,0.0,10.0,0.0,2416.0,...,0,1,1,0,1,0,1,0,1,0
29,23925.0,0.1240,537.05,93000.0,15.77,0.0,0.0,10.0,0.0,1697.0,...,1,1,0,1,1,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12150,15000.0,0.1695,372.39,110000.0,7.48,0.0,3.0,15.0,0.0,5735.0,...,1,1,0,1,1,0,1,0,1,0
12151,6000.0,0.1171,198.46,57000.0,15.56,0.0,0.0,15.0,0.0,5106.0,...,0,1,0,1,1,0,0,1,1,0
12152,21275.0,0.2055,570.19,82000.0,36.67,0.0,0.0,14.0,0.0,30141.0,...,0,1,0,1,0,1,1,0,1,0
12153,25525.0,0.2305,988.74,57256.0,42.99,0.0,1.0,12.0,0.0,26040.0,...,0,1,0,1,0,1,1,0,1,0
12154,14875.0,0.2055,398.67,66000.0,14.58,0.0,0.0,5.0,0.0,9994.0,...,0,1,0,1,1,0,1,0,1,0
12155,35000.0,0.2565,1403.66,183000.0,17.74,0.0,5.0,13.0,0.0,24598.0,...,0,1,0,1,0,1,1,0,1,0
12156,5000.0,0.2565,200.53,30000.0,35.22,2.0,1.0,17.0,0.0,6577.0,...,0,1,0,1,1,0,1,0,1,0
12157,23225.0,0.1612,566.27,162000.0,25.06,1.0,1.0,7.0,0.0,27980.0,...,0,1,0,1,1,0,1,0,1,0
12158,8000.0,0.1774,288.18,34000.0,21.64,0.0,1.0,5.0,0.0,5483.0,...,0,1,0,1,1,0,1,0,1,0
12159,17000.0,0.1524,406.58,80000.0,19.49,0.0,1.0,22.0,0.0,14292.0,...,0,1,0,1,1,0,1,0,1,0
12160,8000.0,0.1695,285.03,75000.0,22.54,2.0,1.0,14.0,0.0,5346.0,...,0,1,0,1,1,0,1,0,1,0
12161,14875.0,0.1308,339.07,110000.0,35.05,0.0,1.0,13.0,0.0,22482.0,...,1,1,1,0,1,0,1,0,1,0
12162,30000.0,0.1862,1093.93,178076.0,30.66,0.0,2.0,18.0,0.0,40295.0,...,0,1,0,1,0,1,1,0,1,0
12163,26450.0,0.1695,942.36,30000.0,27.44,0.0,0.0,5.0,0.0,797.0,...,0,1,1,0,0,1,1,0,1,0
12164,20000.0,0.1102,654.97,40000.0,9.42,0.0,1.0,41.0,0.0,15049.0,...,0,1,0,1,1,0,1,0,1,0
12165,7500.0,0.1612,264.13,87000.0,7.63,0.0,0.0,7.0,0.0,201.0,...,0,1,0,1,1,0,1,0,1,0
12166,36800.0,0.1102,800.49,80000.0,16.46,0.0,0.0,6.0,0.0,18437.0,...,1,1,0,1,1,0,1,0,1,0
12167,40000.0,0.0646,1225.24,100000.0,20.81,0.0,1.0,23.0,0.0,36955.0,...,0,1,0,1,1,0,1,0,1,0
12168,36000.0,0.0819,733.23,100000.0,20.14,0.0,1.0,18.0,0.0,28813.0,...,0,1,0,1,1,0,1,0,1,0
12169,25000.0,0.1524,597.91,45000.0,56.59,0.0,0.0,17.0,0.0,20709.0,...,1,1,0,1,0,1,1,0,1,0
12170,35000.0,0.2055,1310.56,34000.0,26.96,0.0,3.0,6.0,0.0,1575.0,...,1,1,0,1,0,1,1,0,1,0
12171,24000.0,0.1033,513.84,125000.0,37.50,0.0,0.0,17.0,0.0,62564.0,...,0,1,0,1,1,0,1,0,1,0
12172,15000.0,0.1774,540.34,42000.0,24.86,1.0,1.0,15.0,0.0,15230.0,...,1,1,0,1,1,0,1,0,1,0
12173,20000.0,0.1774,720.45,66000.0,33.36,0.0,0.0,9.0,0.0,23571.0,...,1,1,0,1,1,0,1,0,1,0
12174,15000.0,0.1033,321.15,60000.0,12.52,0.0,0.0,13.0,0.0,9270.0,...,1,1,0,1,1,0,1,0,1,0
12175,19975.0,0.2565,801.09,28000.0,28.42,0.0,0.0,15.0,0.0,9679.0,...,0,1,0,1,1,0,1,0,1,0
12176,15000.0,0.1774,540.34,50000.0,23.43,4.0,0.0,16.0,0.0,3193.0,...,1,1,0,1,1,0,1,0,1,0
12177,3600.0,0.1862,131.28,60000.0,28.80,0.0,1.0,14.0,0.0,11804.0,...,0,1,0,1,1,0,1,0,1,0
12178,15000.0,0.0881,475.68,62000.0,11.44,0.0,0.0,5.0,0.0,157.0,...,0,1,0,1,0,1,1,0,1,0
12179,15000.0,0.1774,540.34,54080.0,21.66,1.0,1.0,5.0,0.0,8349.0,...,0,1,1,0,1,0,1,0,1,0

In [30]:
X_dummies.columns

Index(['loan_amnt', 'int_rate', 'installment', 'annual_inc', 'dti',
       'delinq_2yrs', 'inq_last_6mths', 'open_acc', 'pub_rec', 'revol_bal',
       'total_acc', 'out_prncp', 'out_prncp_inv', 'total_pymnt',
       'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int',
       'total_rec_late_fee', 'recoveries', 'collection_recovery_fee',
       'last_pymnt_amnt', 'collections_12_mths_ex_med', 'policy_code',
       'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'open_acc_6m',
       'open_act_il', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il',
       'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m', 'max_bal_bc',
       'all_util', 'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m',
       'acc_open_past_24mths', 'avg_cur_bal', 'bc_open_to_buy', 'bc_util',
       'chargeoff_within_12_mths', 'delinq_amnt', 'mo_sin_old_il_acct',
       'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl',
       'mort_acc', 'mths_since_recent_bc', 'mths_since_recent_inq',
       'num_accts_ever_120_pd', 'num_actv_bc_tl', 'num_actv_rev_tl',
       'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl',
       'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_sats', 'num_tl_120dpd_2m',
       'num_tl_30dpd', 'num_tl_90g_dpd_24m', 'num_tl_op_past_12m',
       'pct_tl_nvr_dlq', 'percent_bc_gt_75', 'pub_rec_bankruptcies',
       'tax_liens', 'tot_hi_cred_lim', 'total_bal_ex_mort', 'total_bc_limit',
       'total_il_high_credit_limit', 'home_ownership_ANY',
       'home_ownership_MORTGAGE', 'home_ownership_OWN', 'home_ownership_RENT',
       'verification_status_Not Verified',
       'verification_status_Source Verified', 'verification_status_Verified',
       'pymnt_plan_n', 'initial_list_status_f', 'initial_list_status_w',
       'application_type_Individual', 'application_type_Joint App',
       'hardship_flag_N', 'hardship_flag_Y', 'debt_settlement_flag_N',
       'debt_settlement_flag_Y'],
      dtype='object')

##### Testing Data Set

In [31]:
# Removing target feature from testing data
X_test = test_df[['loan_amnt', 'int_rate', 'installment', 'home_ownership', 'annual_inc',
       'verification_status', 'pymnt_plan', 'dti', 'delinq_2yrs',
       'inq_last_6mths', 'open_acc', 'pub_rec', 'revol_bal', 'total_acc',
       'initial_list_status', 'out_prncp', 'out_prncp_inv', 'total_pymnt',
       'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int',
       'total_rec_late_fee', 'recoveries', 'collection_recovery_fee',
       'last_pymnt_amnt', 'collections_12_mths_ex_med', 'policy_code',
       'application_type', 'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal',
       'open_acc_6m', 'open_act_il', 'open_il_12m', 'open_il_24m',
       'mths_since_rcnt_il', 'total_bal_il', 'il_util', 'open_rv_12m',
       'open_rv_24m', 'max_bal_bc', 'all_util', 'total_rev_hi_lim', 'inq_fi',
       'total_cu_tl', 'inq_last_12m', 'acc_open_past_24mths', 'avg_cur_bal',
       'bc_open_to_buy', 'bc_util', 'chargeoff_within_12_mths', 'delinq_amnt',
       'mo_sin_old_il_acct', 'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op',
       'mo_sin_rcnt_tl', 'mort_acc', 'mths_since_recent_bc',
       'mths_since_recent_inq', 'num_accts_ever_120_pd', 'num_actv_bc_tl',
       'num_actv_rev_tl', 'num_bc_sats', 'num_bc_tl', 'num_il_tl',
       'num_op_rev_tl', 'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_sats',
       'num_tl_120dpd_2m', 'num_tl_30dpd', 'num_tl_90g_dpd_24m',
       'num_tl_op_past_12m', 'pct_tl_nvr_dlq', 'percent_bc_gt_75',
       'pub_rec_bankruptcies', 'tax_liens', 'tot_hi_cred_lim',
       'total_bal_ex_mort', 'total_bc_limit', 'total_il_high_credit_limit',
       'hardship_flag', 'debt_settlement_flag']]

In [32]:
 # Convert categorical data to numeric and separate target feature for testing data
X_test = pd.get_dummies(X_test)
X_test

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,verification_status_Source Verified,verification_status_Verified,pymnt_plan_n,initial_list_status_f,initial_list_status_w,application_type_Individual,application_type_Joint App,hardship_flag_N,hardship_flag_Y,debt_settlement_flag_N
0,40000.0,0.1033,856.40,128700.0,12.47,0.0,1.0,8.0,0.0,38113.0,...,1,0,1,0,1,1,0,0,1,1
1,24450.0,0.1430,572.72,44574.0,15.05,0.0,1.0,6.0,0.0,1665.0,...,0,0,1,0,1,1,0,1,0,1
2,13500.0,0.1430,316.23,60000.0,28.72,0.0,0.0,8.0,0.0,13857.0,...,0,0,1,0,1,1,0,0,1,1
3,10625.0,0.1774,268.31,60000.0,15.70,0.0,4.0,17.0,0.0,6216.0,...,0,1,1,0,1,1,0,1,0,1
4,6375.0,0.1862,232.46,60000.0,35.50,0.0,0.0,13.0,0.0,12681.0,...,1,0,1,0,1,1,0,1,0,1
5,15000.0,0.1102,491.23,45000.0,66.32,0.0,0.0,8.0,0.0,6647.0,...,1,0,1,0,1,0,1,1,0,1
6,12000.0,0.0702,370.64,81500.0,16.61,0.0,0.0,13.0,1.0,10395.0,...,1,0,1,0,1,1,0,1,0,1
7,4500.0,0.1308,151.80,95000.0,24.36,0.0,0.0,21.0,0.0,34540.0,...,1,0,1,0,1,1,0,1,0,1
8,8000.0,0.1033,259.38,50000.0,13.18,0.0,0.0,4.0,0.0,14519.0,...,0,0,1,0,1,1,0,1,0,1
9,40000.0,0.0646,1225.24,140000.0,16.38,0.0,0.0,21.0,0.0,49666.0,...,1,0,1,0,1,1,0,1,0,1
10,30000.0,0.1033,972.68,104000.0,28.12,0.0,1.0,22.0,0.0,38663.0,...,0,0,1,0,1,1,0,1,0,1
11,32000.0,0.0819,651.76,91935.0,29.27,0.0,0.0,22.0,0.0,54496.0,...,0,1,1,0,1,1,0,1,0,1
12,20000.0,0.0646,612.62,155000.0,13.70,0.0,1.0,10.0,0.0,5432.0,...,0,0,1,0,1,1,0,1,0,1
13,6500.0,0.0646,199.11,79000.0,8.87,0.0,0.0,12.0,0.0,6959.0,...,1,0,1,0,1,1,0,1,0,1
14,40000.0,0.0756,1245.36,120000.0,17.48,0.0,0.0,15.0,0.0,83320.0,...,0,0,1,0,1,0,1,1,0,1
15,4000.0,0.0881,126.85,61500.0,15.55,0.0,0.0,6.0,0.0,15472.0,...,0,0,1,0,1,1,0,1,0,1
16,24000.0,0.1430,562.18,63250.0,21.84,0.0,0.0,5.0,0.0,1351.0,...,0,1,1,0,1,1,0,1,0,1
17,17000.0,0.0819,534.21,65000.0,28.42,0.0,0.0,11.0,0.0,5955.0,...,0,0,1,0,1,1,0,1,0,1
18,4000.0,0.2055,149.78,20000.0,20.41,0.0,0.0,6.0,0.0,3394.0,...,1,0,1,0,1,1,0,1,0,1
19,21275.0,0.0819,668.55,114000.0,38.20,0.0,0.0,27.0,0.0,29992.0,...,0,0,1,0,1,1,0,1,0,1
20,8000.0,0.0646,245.05,26000.0,28.25,0.0,0.0,7.0,1.0,9986.0,...,0,0,1,0,1,1,0,1,0,1
21,24000.0,0.2565,713.61,47000.0,20.48,0.0,0.0,7.0,0.0,8939.0,...,0,1,1,0,1,1,0,1,0,1
22,24000.0,0.1524,573.99,43600.0,24.27,0.0,0.0,9.0,0.0,22513.0,...,0,0,1,0,1,1,0,1,0,1
23,10525.0,0.0756,327.69,72000.0,36.33,0.0,0.0,13.0,0.0,15260.0,...,1,0,1,0,1,1,0,1,0,1
24,10000.0,0.1308,337.33,70000.0,11.31,0.0,0.0,8.0,0.0,9613.0,...,0,0,1,0,1,1,0,1,0,1
25,24000.0,0.1240,538.74,65004.0,25.53,0.0,0.0,12.0,0.0,16237.0,...,1,0,1,0,1,1,0,1,0,1
26,21275.0,0.1171,703.70,90000.0,40.89,0.0,1.0,13.0,0.0,7471.0,...,0,0,1,1,0,0,1,1,0,1
27,10625.0,0.1862,387.44,175000.0,7.64,0.0,2.0,11.0,0.0,11681.0,...,0,0,1,0,1,1,0,1,0,1
28,15000.0,0.2305,581.04,65000.0,34.18,0.0,1.0,15.0,0.0,40123.0,...,0,0,1,0,1,1,0,1,0,1
29,31900.0,0.1033,682.98,78642.0,16.41,0.0,0.0,7.0,0.0,10049.0,...,1,0,1,0,1,1,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4672,20000.0,0.2055,536.02,130000.0,12.72,1.0,0.0,9.0,0.0,5209.0,...,1,0,1,0,1,1,0,1,0,1
4673,15000.0,0.1430,351.37,85000.0,17.42,0.0,2.0,8.0,0.0,17247.0,...,1,0,1,0,1,1,0,1,0,1
4674,4800.0,0.2305,185.94,45000.0,32.93,1.0,1.0,10.0,1.0,3113.0,...,0,0,1,0,1,1,0,1,0,1
4675,7000.0,0.2305,271.16,30000.0,24.64,0.0,1.0,6.0,0.0,7266.0,...,0,0,1,0,1,1,0,1,0,1
4676,10000.0,0.1171,330.76,32000.0,20.33,0.0,0.0,7.0,1.0,7666.0,...,0,0,1,0,1,1,0,1,0,1
4677,20000.0,0.2055,536.02,80000.0,20.25,0.0,3.0,16.0,0.0,17614.0,...,1,0,1,0,1,1,0,1,0,1
4678,21275.0,0.1774,766.38,298000.0,11.96,0.0,1.0,18.0,0.0,30756.0,...,0,0,1,0,1,1,0,1,0,1
4679,21275.0,0.1774,766.38,195000.0,14.75,0.0,0.0,9.0,0.0,5861.0,...,1,0,1,0,1,1,0,1,0,1
4680,32925.0,0.2305,929.12,150000.0,20.92,0.0,1.0,10.0,0.0,27282.0,...,0,0,1,0,1,1,0,1,0,1
4681,35000.0,0.2055,938.03,125000.0,8.07,0.0,0.0,9.0,0.0,14567.0,...,0,0,1,0,1,1,0,1,0,1
4682,10625.0,0.1695,378.55,45000.0,31.63,0.0,1.0,12.0,1.0,23734.0,...,0,0,1,0,1,1,0,1,0,1
4683,25000.0,0.2305,968.40,155000.0,37.38,0.0,1.0,15.0,0.0,43930.0,...,0,1,1,0,1,1,0,1,0,1
4684,29000.0,0.0819,590.66,75000.0,12.72,0.0,0.0,4.0,0.0,19291.0,...,0,0,1,0,1,1,0,1,0,1
4685,3000.0,0.0819,94.28,40000.0,26.31,0.0,2.0,9.0,0.0,2090.0,...,0,0,1,0,1,1,0,1,0,1
4686,16000.0,0.1695,397.22,95000.0,12.44,0.0,1.0,15.0,0.0,15605.0,...,0,0,1,0,1,1,0,1,0,1
4687,20000.0,0.2305,564.39,53000.0,30.62,0.0,0.0,10.0,0.0,20185.0,...,0,1,1,0,1,1,0,1,0,1
4688,18000.0,0.0702,555.96,96000.0,17.32,0.0,1.0,17.0,0.0,17928.0,...,0,0,1,0,1,1,0,1,0,1
4689,20000.0,0.1102,435.05,80000.0,25.23,0.0,1.0,17.0,0.0,17952.0,...,0,0,1,0,1,1,0,1,0,1
4690,25000.0,0.2055,670.03,80004.0,15.06,0.0,0.0,12.0,0.0,5950.0,...,0,0,1,1,0,1,0,1,0,1
4691,30000.0,0.2880,948.61,180000.0,12.74,0.0,0.0,16.0,0.0,24589.0,...,0,0,1,0,1,1,0,1,0,1
4692,40000.0,0.1240,1336.23,201000.0,15.60,0.0,0.0,34.0,0.0,40589.0,...,1,0,1,0,1,1,0,1,0,1
4693,3000.0,0.2055,112.34,84996.0,13.64,0.0,0.0,10.0,0.0,4388.0,...,1,0,1,0,1,1,0,1,0,1
4694,3000.0,0.1524,104.35,28400.0,24.09,0.0,1.0,5.0,0.0,2928.0,...,1,0,1,0,1,1,0,1,0,1
4695,16000.0,0.2055,599.12,110000.0,15.88,1.0,2.0,6.0,0.0,4241.0,...,0,1,1,1,0,1,0,1,0,1
4696,10000.0,0.1171,330.76,101853.0,13.76,0.0,1.0,9.0,0.0,4482.0,...,1,0,1,0,1,1,0,1,0,1
4697,30000.0,0.1240,673.42,140480.0,15.74,0.0,0.0,20.0,0.0,23215.0,...,1,0,1,1,0,1,0,1,0,1
4698,24000.0,0.0756,747.22,50000.0,26.81,0.0,0.0,9.0,0.0,459.0,...,0,0,1,0,1,1,0,1,0,1
4699,10000.0,0.2305,387.36,33000.0,38.51,0.0,2.0,7.0,0.0,6342.0,...,0,1,1,1,0,1,0,1,0,1
4700,8000.0,0.1862,205.86,38000.0,16.36,0.0,1.0,8.0,1.0,11636.0,...,1,0,1,0,1,1,0,1,0,1
4701,30000.0,0.2055,1123.34,180000.0,12.06,0.0,0.0,8.0,0.0,4771.0,...,1,0,1,1,0,1,0,1,0,1

In [33]:
# Separate target feature for testing data
y_test = test_df[['target']]
test_y_label = LabelEncoder().fit_transform(y_test['target'])
test_y_label

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

In [34]:
#Finding mission value
missing = set(X_dummies)-set(X_test)
missing

{'debt_settlement_flag_Y'}

In [35]:
# add missing dummy variables to testing set
X_test['debt_settlement_flag_Y'] = 0
X_test

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,verification_status_Verified,pymnt_plan_n,initial_list_status_f,initial_list_status_w,application_type_Individual,application_type_Joint App,hardship_flag_N,hardship_flag_Y,debt_settlement_flag_N,debt_settlement_flag_Y
0,40000.0,0.1033,856.40,128700.0,12.47,0.0,1.0,8.0,0.0,38113.0,...,0,1,0,1,1,0,0,1,1,0
1,24450.0,0.1430,572.72,44574.0,15.05,0.0,1.0,6.0,0.0,1665.0,...,0,1,0,1,1,0,1,0,1,0
2,13500.0,0.1430,316.23,60000.0,28.72,0.0,0.0,8.0,0.0,13857.0,...,0,1,0,1,1,0,0,1,1,0
3,10625.0,0.1774,268.31,60000.0,15.70,0.0,4.0,17.0,0.0,6216.0,...,1,1,0,1,1,0,1,0,1,0
4,6375.0,0.1862,232.46,60000.0,35.50,0.0,0.0,13.0,0.0,12681.0,...,0,1,0,1,1,0,1,0,1,0
5,15000.0,0.1102,491.23,45000.0,66.32,0.0,0.0,8.0,0.0,6647.0,...,0,1,0,1,0,1,1,0,1,0
6,12000.0,0.0702,370.64,81500.0,16.61,0.0,0.0,13.0,1.0,10395.0,...,0,1,0,1,1,0,1,0,1,0
7,4500.0,0.1308,151.80,95000.0,24.36,0.0,0.0,21.0,0.0,34540.0,...,0,1,0,1,1,0,1,0,1,0
8,8000.0,0.1033,259.38,50000.0,13.18,0.0,0.0,4.0,0.0,14519.0,...,0,1,0,1,1,0,1,0,1,0
9,40000.0,0.0646,1225.24,140000.0,16.38,0.0,0.0,21.0,0.0,49666.0,...,0,1,0,1,1,0,1,0,1,0
10,30000.0,0.1033,972.68,104000.0,28.12,0.0,1.0,22.0,0.0,38663.0,...,0,1,0,1,1,0,1,0,1,0
11,32000.0,0.0819,651.76,91935.0,29.27,0.0,0.0,22.0,0.0,54496.0,...,1,1,0,1,1,0,1,0,1,0
12,20000.0,0.0646,612.62,155000.0,13.70,0.0,1.0,10.0,0.0,5432.0,...,0,1,0,1,1,0,1,0,1,0
13,6500.0,0.0646,199.11,79000.0,8.87,0.0,0.0,12.0,0.0,6959.0,...,0,1,0,1,1,0,1,0,1,0
14,40000.0,0.0756,1245.36,120000.0,17.48,0.0,0.0,15.0,0.0,83320.0,...,0,1,0,1,0,1,1,0,1,0
15,4000.0,0.0881,126.85,61500.0,15.55,0.0,0.0,6.0,0.0,15472.0,...,0,1,0,1,1,0,1,0,1,0
16,24000.0,0.1430,562.18,63250.0,21.84,0.0,0.0,5.0,0.0,1351.0,...,1,1,0,1,1,0,1,0,1,0
17,17000.0,0.0819,534.21,65000.0,28.42,0.0,0.0,11.0,0.0,5955.0,...,0,1,0,1,1,0,1,0,1,0
18,4000.0,0.2055,149.78,20000.0,20.41,0.0,0.0,6.0,0.0,3394.0,...,0,1,0,1,1,0,1,0,1,0
19,21275.0,0.0819,668.55,114000.0,38.20,0.0,0.0,27.0,0.0,29992.0,...,0,1,0,1,1,0,1,0,1,0
20,8000.0,0.0646,245.05,26000.0,28.25,0.0,0.0,7.0,1.0,9986.0,...,0,1,0,1,1,0,1,0,1,0
21,24000.0,0.2565,713.61,47000.0,20.48,0.0,0.0,7.0,0.0,8939.0,...,1,1,0,1,1,0,1,0,1,0
22,24000.0,0.1524,573.99,43600.0,24.27,0.0,0.0,9.0,0.0,22513.0,...,0,1,0,1,1,0,1,0,1,0
23,10525.0,0.0756,327.69,72000.0,36.33,0.0,0.0,13.0,0.0,15260.0,...,0,1,0,1,1,0,1,0,1,0
24,10000.0,0.1308,337.33,70000.0,11.31,0.0,0.0,8.0,0.0,9613.0,...,0,1,0,1,1,0,1,0,1,0
25,24000.0,0.1240,538.74,65004.0,25.53,0.0,0.0,12.0,0.0,16237.0,...,0,1,0,1,1,0,1,0,1,0
26,21275.0,0.1171,703.70,90000.0,40.89,0.0,1.0,13.0,0.0,7471.0,...,0,1,1,0,0,1,1,0,1,0
27,10625.0,0.1862,387.44,175000.0,7.64,0.0,2.0,11.0,0.0,11681.0,...,0,1,0,1,1,0,1,0,1,0
28,15000.0,0.2305,581.04,65000.0,34.18,0.0,1.0,15.0,0.0,40123.0,...,0,1,0,1,1,0,1,0,1,0
29,31900.0,0.1033,682.98,78642.0,16.41,0.0,0.0,7.0,0.0,10049.0,...,0,1,0,1,1,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4672,20000.0,0.2055,536.02,130000.0,12.72,1.0,0.0,9.0,0.0,5209.0,...,0,1,0,1,1,0,1,0,1,0
4673,15000.0,0.1430,351.37,85000.0,17.42,0.0,2.0,8.0,0.0,17247.0,...,0,1,0,1,1,0,1,0,1,0
4674,4800.0,0.2305,185.94,45000.0,32.93,1.0,1.0,10.0,1.0,3113.0,...,0,1,0,1,1,0,1,0,1,0
4675,7000.0,0.2305,271.16,30000.0,24.64,0.0,1.0,6.0,0.0,7266.0,...,0,1,0,1,1,0,1,0,1,0
4676,10000.0,0.1171,330.76,32000.0,20.33,0.0,0.0,7.0,1.0,7666.0,...,0,1,0,1,1,0,1,0,1,0
4677,20000.0,0.2055,536.02,80000.0,20.25,0.0,3.0,16.0,0.0,17614.0,...,0,1,0,1,1,0,1,0,1,0
4678,21275.0,0.1774,766.38,298000.0,11.96,0.0,1.0,18.0,0.0,30756.0,...,0,1,0,1,1,0,1,0,1,0
4679,21275.0,0.1774,766.38,195000.0,14.75,0.0,0.0,9.0,0.0,5861.0,...,0,1,0,1,1,0,1,0,1,0
4680,32925.0,0.2305,929.12,150000.0,20.92,0.0,1.0,10.0,0.0,27282.0,...,0,1,0,1,1,0,1,0,1,0
4681,35000.0,0.2055,938.03,125000.0,8.07,0.0,0.0,9.0,0.0,14567.0,...,0,1,0,1,1,0,1,0,1,0
4682,10625.0,0.1695,378.55,45000.0,31.63,0.0,1.0,12.0,1.0,23734.0,...,0,1,0,1,1,0,1,0,1,0
4683,25000.0,0.2305,968.40,155000.0,37.38,0.0,1.0,15.0,0.0,43930.0,...,1,1,0,1,1,0,1,0,1,0
4684,29000.0,0.0819,590.66,75000.0,12.72,0.0,0.0,4.0,0.0,19291.0,...,0,1,0,1,1,0,1,0,1,0
4685,3000.0,0.0819,94.28,40000.0,26.31,0.0,2.0,9.0,0.0,2090.0,...,0,1,0,1,1,0,1,0,1,0
4686,16000.0,0.1695,397.22,95000.0,12.44,0.0,1.0,15.0,0.0,15605.0,...,0,1,0,1,1,0,1,0,1,0
4687,20000.0,0.2305,564.39,53000.0,30.62,0.0,0.0,10.0,0.0,20185.0,...,1,1,0,1,1,0,1,0,1,0
4688,18000.0,0.0702,555.96,96000.0,17.32,0.0,1.0,17.0,0.0,17928.0,...,0,1,0,1,1,0,1,0,1,0
4689,20000.0,0.1102,435.05,80000.0,25.23,0.0,1.0,17.0,0.0,17952.0,...,0,1,0,1,1,0,1,0,1,0
4690,25000.0,0.2055,670.03,80004.0,15.06,0.0,0.0,12.0,0.0,5950.0,...,0,1,1,0,1,0,1,0,1,0
4691,30000.0,0.2880,948.61,180000.0,12.74,0.0,0.0,16.0,0.0,24589.0,...,0,1,0,1,1,0,1,0,1,0
4692,40000.0,0.1240,1336.23,201000.0,15.60,0.0,0.0,34.0,0.0,40589.0,...,0,1,0,1,1,0,1,0,1,0
4693,3000.0,0.2055,112.34,84996.0,13.64,0.0,0.0,10.0,0.0,4388.0,...,0,1,0,1,1,0,1,0,1,0
4694,3000.0,0.1524,104.35,28400.0,24.09,0.0,1.0,5.0,0.0,2928.0,...,0,1,0,1,1,0,1,0,1,0
4695,16000.0,0.2055,599.12,110000.0,15.88,1.0,2.0,6.0,0.0,4241.0,...,1,1,1,0,1,0,1,0,1,0
4696,10000.0,0.1171,330.76,101853.0,13.76,0.0,1.0,9.0,0.0,4482.0,...,0,1,0,1,1,0,1,0,1,0
4697,30000.0,0.1240,673.42,140480.0,15.74,0.0,0.0,20.0,0.0,23215.0,...,0,1,1,0,1,0,1,0,1,0
4698,24000.0,0.0756,747.22,50000.0,26.81,0.0,0.0,9.0,0.0,459.0,...,0,1,0,1,1,0,1,0,1,0
4699,10000.0,0.2305,387.36,33000.0,38.51,0.0,2.0,7.0,0.0,6342.0,...,1,1,1,0,1,0,1,0,1,0
4700,8000.0,0.1862,205.86,38000.0,16.36,0.0,1.0,8.0,1.0,11636.0,...,0,1,0,1,1,0,1,0,1,0
4701,30000.0,0.2055,1123.34,180000.0,12.06,0.0,0.0,8.0,0.0,4771.0,...,0,1,1,0,1,0,1,0,1,0

### LogisticRegression Model

In [36]:
# X and y shape
print("Shape: ", X_dummies.shape, y_label.shape)

Shape:  (12180, 92) (12180,)

#### Train the Logistic Regression model on the unscaled data and print the model score

In [37]:
# Create a logistic regression model
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [38]:
# Fit/train the model to the data
classifier.fit(X_dummies, y_label)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [39]:
# Print the accuracy score for the test data (Validate)
print(f"Training Data Score: {classifier.score(X_dummies, y_label)}")
print(f"Testing Data Score: {classifier.score(X_test, test_y_label)}")

Training Data Score: 0.7096059113300492
Testing Data Score: 0.5582730752871119

In [40]:
# Make predictions by using the X_test and y_test data
pd.DataFrame({
    "actual": list(test_y_label),
    "predicted": list(classifier.predict(X_test))
})

      actual  predicted
0          1          0
1          1          1
2          1          0
3          1          0
4          1          1
5          1          1
6          1          1
7          1          1
8          1          1
9          1          1
10         1          1
11         1          1
12         1          1
13         1          0
14         1          1
15         1          1
16         1          1
17         1          1
18         1          1
19         1          1
20         1          1
21         1          0
22         1          0
23         1          1
24         1          1
25         1          1
26         1          0
27         1          0
28         1          0
29         1          1
...      ...        ...
4672       0          0
4673       0          0
4674       0          1
4675       0          0
4676       0          1
4677       0          1
4678       0          0
4679       0          1
4680       0          1
4681       0          1
4682       0          1
4683       0          0
4684       0          1
4685       0          1
4686       0          1
4687       0          0
4688       0          1
4689       0          1
4690       0          1
4691       0          0
4692       0          1
4693       0          1
4694       0          1
4695       0          0
4696       0          0
4697       0          0
4698       0          1
4699       0          1
4700       0          1
4701       0          0

[4702 rows x 2 columns]

In [41]:
# Create a confusion matrix on the test data
# Use the true values from test_y_label and the output of the model with X_test as the input
from sklearn.metrics import confusion_matrix
y_true = test_y_label
y_pred = classifier.predict(X_test)
confusion_matrix(y_true, y_pred)

array([[ 827, 1524],
       [ 553, 1798]], dtype=int64)

#### Train a Random Forest Classifier model and print the model score

In [42]:
# Import a Random Forests classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

In [43]:
# Fit a model, and then print a classification report
clf = RandomForestClassifier(random_state=1).fit(X_dummies, y_label)
y_pred_2 = clf.predict(X_test)
print(classification_report(test_y_label, y_pred_2, target_names=['low_risk','high_risk']))
print(f'Training Score: {clf.score(X_dummies, y_label)}')
print(f'Testing Score: {clf.score(X_test, test_y_label)}')

             precision    recall  f1-score   support

   low_risk       0.57      0.80      0.67      2351
  high_risk       0.66      0.39      0.49      2351

avg / total       0.62      0.60      0.58      4702

Training Score: 0.9859605911330049
Testing Score: 0.597618034878775

### Scale the data

In [44]:
# Scale the data with StandardScaler()
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler().fit(X_dummies)
X_train_scaled = scaler.transform(X_dummies)
X_test_scaled = scaler.transform(X_test)

#### Train the Logistic Regression model on the scaled data and print the model score

In [45]:
# Create a logistic regression model
classifier2 = LogisticRegression()
classifier2

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [46]:
# Fit/train the model to the data
classifier.fit(X_train_scaled, y_label)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [47]:
# Print the accuracy score for the test data (Validate)
print(f"Training Data Score: {classifier.score(X_train_scaled, y_label)}")
print(f"Testing Data Score: {classifier.score(X_test_scaled, test_y_label)}")

Training Data Score: 0.7108374384236453
Testing Data Score: 0.75903870693322

In [48]:
# Make predictions by using the X_test and y_test data
pd.DataFrame({
    "actual": list(test_y_label),
    "predicted": list(classifier.predict(X_test_scaled))
})

      actual  predicted
0          1          0
1          1          1
2          1          0
3          1          0
4          1          1
5          1          1
6          1          1
7          1          1
8          1          1
9          1          1
10         1          1
11         1          1
12         1          1
13         1          0
14         1          1
15         1          1
16         1          1
17         1          1
18         1          1
19         1          1
20         1          1
21         1          0
22         1          0
23         1          1
24         1          1
25         1          1
26         1          1
27         1          0
28         1          0
29         1          1
...      ...        ...
4672       0          0
4673       0          0
4674       0          0
4675       0          0
4676       0          0
4677       0          0
4678       0          0
4679       0          0
4680       0          0
4681       0          0
4682       0          0
4683       0          0
4684       0          1
4685       0          0
4686       0          0
4687       0          0
4688       0          0
4689       0          0
4690       0          0
4691       0          0
4692       0          0
4693       0          1
4694       0          0
4695       0          0
4696       0          1
4697       0          0
4698       0          0
4699       0          0
4700       0          0
4701       0          0

[4702 rows x 2 columns]

In [49]:
# Create a confusion matrix on the test data
y_true = test_y_label
y_pred = classifier.predict(X_test_scaled)
confusion_matrix(y_true, y_pred)

array([[1758,  593],
       [ 540, 1811]], dtype=int64)

#### Train a Random Forest Classifier model on the scaled data and print the model score

In [50]:
# Fit a model, and then print a classification report
clf = RandomForestClassifier(random_state=1).fit(X_train_scaled, y_label)
y_pred_2 = clf.predict(X_test_scaled)
print(classification_report(test_y_label, y_pred_2, target_names=['low_risk','high_risk']))
print(f'Training Score: {clf.score(X_train_scaled, y_label)}')
print(f'Testing Score: {clf.score(X_test_scaled, test_y_label)}')

             precision    recall  f1-score   support

   low_risk       0.57      0.80      0.67      2351
  high_risk       0.66      0.39      0.49      2351

avg / total       0.62      0.60      0.58      4702

Training Score: 0.9859605911330049
Testing Score: 0.5974053594215227